apiVersion: v1
kind: Pod
metadata:
  name: matts-python-pod
  labels:
    zone: prod
    version: v1
spec: 
  containers:
  - name: python-ctr
    image: sudirlay/images:matt-python-demo
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "1"
  restartPolicy: Never
 
